// Sonic Project 06.h
// Generated by decompiling Sonic Project 06.asm
// using Reko decompiler version 0.10.0.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals @ 00000000 : (ptr64 (struct "Globals")))
// Type Variables ////////////
globals_t: (in globals @ 00000000 : (ptr64 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr64 Eq_1)
  OrigDataType: (ptr64 (struct "Globals"))
*/
typedef struct Globals {
} Eq_1;

